04-long-parameter-list/havenkim/haven-long-parameter-list.md

[편하게 보기](https://github.com/raacker/book-study-refactoring/blob/04-long-parameter/04-long-parameter-list/havenkim/haven-long-parameter-list.md)

Long Parameter List

---

01-mysterious-name/brianlee/brian-mystrious-name.md
02-duplicated-code/brianlee/brian-duplicated-code.md
03-long-function/brianlee/brian-long-function.md

Mysterious Name and Duplicated Code

[Brian Lee] Mysterious Name and Duplicated Code

---

02-duplicated-code/yejin-duplicated-code.md
03-long-function/yejin-long-function.md
04-long-parameter-list/yejin-long-parameter-list.md

[Yejin] duplicated code, long function, long parameter list

[Yejin] duplicated code, long function, long parameter list

---

01-mysterious-name/yongju-mystrious-name.md
02-duplicated-code/yongju-duplicated-code.md
03-long-function/yongju-long-function.md
04-long-parameter-list/yongju-long-parameter-list.md

편하게 보기
[01-mysterious-name](https://github.com/yongjukwon/book-study-refactoring/blob/main/01-mysterious-name/yongju-mystrious-name.md)
[02-duplicated-code](https://github.com/yongjukwon/book-study-refactoring/blob/main/02-duplicated-code/yongju-duplicated-code.md)
[03-long-function](https://github.com/yongjukwon/book-study-refactoring/blob/main/03-long-function/yongju-long-function.md)
[04-long-parameter-list](https://github.com/yongjukwon/book-study-refactoring/blob/main/04-long-parameter-list/yongju-long-parameter-list.md)

[Yongju] 01-mysterious-name & 04-long-parameter-list

---

09-feature-envy/havenkim/haven-feature-envy.md
10-data-clumps/havenkim/haven-data-clumps.md
11-primitive-obsession/havenkim/haven-primitive-obsession.md
12-repeated-switches/havenkim/haven-repeated-switches.md

[Feature Envy](https://github.com/raacker/book-study-refactoring/blob/week3/09-feature-envy/havenkim/haven-feature-envy.md)
[Data Clumps](https://github.com/raacker/book-study-refactoring/blob/week3/10-data-clumps/havenkim/haven-data-clumps.md)
[Primitive Obsession](https://github.com/raacker/book-study-refactoring/blob/week3/11-primitive-obsession/havenkim/haven-primitive-obsession.md)
[Repeated Switches](https://github.com/raacker/book-study-refactoring/blob/week3/12-repeated-switches/havenkim/haven-repeated-switches.md)

[Haven] Week3

---

01-mysterious-name/yongju-mystrious-name.md
04-long-parameter-list/yongju-long-parameter-list.md
05-global-data/yongju-global-data.md
06-mutable-data/yongju-mutable-data.md
07-divergent-change/yongju-divergent-change.md
08-shotgun-surgery/yongju-shotgun-surgery.md
11-primitive-obsession/yongju-primitive-obsession.md

[Global Data](https://github.com/yongjukwon/book-study-refactoring/blob/main/05-global-data/yongju-global-data.md)
[Mutable Data](https://github.com/yongjukwon/book-study-refactoring/blob/main/06-mutable-data/yongju-mutable-data.md)
[Divergent Change](https://github.com/yongjukwon/book-study-refactoring/blob/main/07-divergent-change/yongju-divergent-change.md)
[Shotgun Surgery](https://github.com/yongjukwon/book-study-refactoring/blob/main/08-shotgun-surgery/yongju-shotgun-surgery.md)

[Yongju] Global Data, Mutable Data, Divergent Change and Shotgun Surgery

---

13-loops/havenkim/haven-loops.md
14-lazy-element/havenkim/haven-lazy-element.md
15-speculative-generality/havenkim/haven-speculative-generality.md
16-temporary-field/havenkim/haven-temporary-field.md

[Loops](https://github.com/raacker/book-study-refactoring/blob/week4/13-loops/havenkim/haven-loops.md)
[Lazy Element](https://github.com/raacker/book-study-refactoring/blob/week4/14-lazy-element/havenkim/haven-lazy-element.md)
[Speculative Generality](https://github.com/raacker/book-study-refactoring/blob/week4/15-speculative-generality/havenkim/haven-speculative-generality.md)
[Temporary Field](https://github.com/raacker/book-study-refactoring/blob/week4/16-temporary-field/havenkim/haven-temporary-field.md)

[Haven] Week4

---

13-loops/yongju-loops.md
14-lazy-element/yongju-lazy-element.md
15-speculative-generality/yongju-speculative-generality.md
16-temporary-field/yongju-temporary-field.md

편하게 보기
[loops](https://github.com/yongjukwon/book-study-refactoring/blob/main/13-loops/yongju-loops.md)
[lazy element](https://github.com/yongjukwon/book-study-refactoring/blob/main/14-lazy-element/yongju-lazy-element.md)
[speculative generality](https://github.com/yongjukwon/book-study-refactoring/blob/main/15-speculative-generality/yongju-speculative-generality.md)
[temporary field](https://github.com/yongjukwon/book-study-refactoring/blob/main/16-temporary-field/yongju-temporary-field.md)

[Yongju] loops, lazy element, speculative generality, and temporary field

---

17-message-chains/havenkim/haven-message-chains.md
18-middle-man/havenkim/haven-middle-man.md
19-insider-trading/havenkim/haven-insider-trading.md
20-large-class/havenkim/haven-large-class.md

[Message Chain](https://github.com/raacker/book-study-refactoring/blob/week5/17-message-chains/havenkim/haven-message-chains.md)
[Middle Man](https://github.com/raacker/book-study-refactoring/blob/week5/18-middle-man/havenkim/haven-middle-man.md)
[Insider Trading](https://github.com/raacker/book-study-refactoring/blob/week5/19-insider-trading/havenkim/haven-insider-trading.md)
[Large Class](https://github.com/raacker/book-study-refactoring/blob/week5/20-large-class/havenkim/haven-large-class.md)

Haven - week 5

---

17-message-chains/yongju-message-chains.md
18-middle-man/yongju-middle-man.md
19-insider-trading/yongju-insider-trading.md
20-large-class/yongju-large-class.md

편하게 보기 
[Message chains](https://github.com/yongjukwon/book-study-refactoring/blob/main/17-message-chains/yongju-message-chains.md)
[Middle man](https://github.com/yongjukwon/book-study-refactoring/blob/main/18-middle-man/yongju-middle-man.md)
[Insider trading](https://github.com/yongjukwon/book-study-refactoring/blob/main/19-insider-trading/yongju-insider-trading.md)
[Large class](https://github.com/yongjukwon/book-study-refactoring/blob/main/20-large-class/yongju-large-class.md)

[Yongju] message chains, middle man, insider trading and large class

---

03-clean-code/03-functions/yongju-functions.md
03-clean-code/04-comments/yongju-comments.md

편하게 보기
[Ch3. Functions](https://github.com/yongjukwon/book-study/blob/main/03-clean-code/03-functions/yongju-functions.md)
[Ch4. Comments](https://github.com/yongjukwon/book-study/blob/main/03-clean-code/04-comments/yongju-comments.md)

[Yongju] functions & comments

---

03-clean-code/05-formatting/yongju-formatting.md
03-clean-code/06-objects-and-data-structures/yongju-objects-and-data-structures.md

편하게보기
[05-formatting](https://github.com/yongjukwon/book-study/blob/main/03-clean-code/05-formatting/yongju-formatting.md)
[06-Objects and Data Structures](https://github.com/yongjukwon/book-study/blob/main/03-clean-code/06-objects-and-data-structures/yongju-objects-and-data-structures.md)

[Yongju] 05-formatting & 06-objects-and-data-structures

---

03-clean-code/07-error-handling/yongju-error-handling.md
03-clean-code/08-boundaries/yongju-boundaries.md

편하게 보기
[07-Error handling](https://github.com/Vancouver-KDD/book-study/blob/main/03-clean-code/07-error-handling/yongju-error-handling.md)
[08-Boundaries](https://github.com/Vancouver-KDD/book-study/blob/main/03-clean-code/08-boundaries/yongju-boundaries.md)

[Yongju] 07-error-handling, 08-boundaries

---

03-clean-code/07-error-handling/davemin-error-handling.md
03-clean-code/08-boundaries/davemin-boundaries.md
03-clean-code/13-concurrency/davemin-concurrency.md
03-clean-code/15-junit-internals/davemin-junit-internals.md

13,15 DAVE

---

04-test-driven-development/chapter-01-multi-currency-money/donggu-ch1-multi-currency.md
04-test-driven-development/chapter-02-degenerate-objects/donggu-ch2-degenerate-objects.md
04-test-driven-development/chapter-03-equality-for-all/donggu-ch3-equality-for-all.md
04-test-driven-development/chapter-04-privacy/donggu-ch4-privacy.md

- TDD week1: Chapter 1 to Chapter 2
-  Renamed folder names

[Donggu Lee] TDD week1

---

04-test-driven-development/chapter-09-times-were-livin-in/donggu-ch9-times-were-livin-in.md
04-test-driven-development/chapter-10-interesting-times/donggu-ch10-interesting-times.md
04-test-driven-development/chapter-11-the-root-of-all-evil/donggu-ch11-the-root-of-all-evil.md
04-test-driven-development/chapter-12-addition-finally/donggu-ch12-addition-finally.md
04-test-driven-development/chapter-13-make-it/donggu-ch13-make-it.md
04-test-driven-development/chapter-14-change/donggu-ch14-change.md
04-test-driven-development/chapter-15-mixed-currencies/donggu-ch15-mixed-currencies.md
04-test-driven-development/chapter-16-abstraction-finally/donggu-ch16-abstraction-finally.md
04-test-driven-development/chapter-17-money-retrospective/donggu-ch17-money-retrospective.md
04-test-driven-development/chapter-18-first-steps-to-xunit/donggu-ch18-first-steps-to-xunit.md
04-test-driven-development/chapter-19-set-the-table/donggu-ch19-set-the-table.md
04-test-driven-development/chapter-20-cleaning-up-after/donggu-ch20-cleaning-up-after.md

[Donggu Lee] TDD week3 and week4

---

04-test-driven-development/chapter-21-counting/donggu-ch21-counting.md
04-test-driven-development/chapter-22-dealing-with-failure/donggu-ch22-dealing-with-failure.md
04-test-driven-development/chapter-23-how-suite-it-is/donggu-ch23-how-suite-it-is.md
04-test-driven-development/chapter-24-xunit-retrospective/donggu-ch24-xunit-retrospective.md

[Donggu Lee] TDD week6

---

04-test-driven-development/chapter-25-test-driven-development-patterns/donggu-ch25-test-driven-development-patterns.md
04-test-driven-development/chapter-26-red-bar-patterns/donggu-ch26-red-bar-patterns.md
04-test-driven-development/chapter-27-testing-patterns/donggu-ch27-testing-patterns.md
04-test-driven-development/chapter-28-green-bar-patterns/donggu-ch28-green-bar-patterns.md

[Donggu Lee] TDD week7

---

README.md

The end date will be added in the near future

Update README.md to include the 2024/Spring bookstudy

---

06-system-design-interview/README.md

Updated the registration link and added an amazon page link to the book.

---

07-designing-data-Intensive-applications/01-reliable-scalable-and-maintainable-applications/jason_yang/01-reliable-scalable-and-maintainable-applications.md
07-designing-data-Intensive-applications/02-data-models-and-query-languages/jason_yang/02-data-models-and-query-languages.md

commit
1. the updated 01-reliable-scalable-and-maintainable-applications.md
2. 02-data-models-and-query-languages.md

02-data-models-and-query-languages.md
